- src/main.tf
https://app.dework.xyz/arrow-air/services-1?taskId=3a1eda78-7f2b-4edc-aede-18aa0d42417c
This is not created from any given template. It is not a library or a service.
Benchmarks may include Python, Rust, Typescript, etc. libraries. We may even be comparing two languages in the same benchmark.
Planned hierarchy:
```tree
benchmarks/
├── client-web
├── server-web
├── deep-learning
└── etc. other benchmarks
```
- `server-web` would include benchmarks for query languages and IPC frameworks/libraries
- `client-web` would include benchmarks for client-side web libraries/frameworks
- `deep-learning` would include benchmarks for deep learning frameworks (Tensorflow, Chainer, MxNet Gluon, etc.) on operations relevant to Arrow
> Add Benchmarks Repo

- src/main.tf
https://app.dework.xyz/arrow-air/services-1/view/board-l4x57ozt?taskId=dc507ba8-6104-4f34-ab46-4d03051101bb
> Add Simulation Tool

- src/templates/all/.editorconfig
- src/templates/all/.make/base.mk
- src/templates/all/.make/docker.mk
- src/templates/all/.make/rust.mk
- src/templates/benchmarks/Makefile
- src/templates/rust-all/Dockerfile
- src/templates/rust-all/Makefile.tftpl
After the refactoring of the make files, we didn't have a `build` and `release` target anymore.
In addition, some fixes were needed for the benchmark repository
> fix(make): combined targets

- src/main.tf
Needs to populate the Rust Makefile
> Add template files to tool-simulation

- src/main.tf
Frontend will be implemented in Vue.
> Create gui demo repo for cargo application

- .editorconfig
- src/repositories_rust.tf
- src/templates/all/.editorconfig
Creating a new svc repository meant to be used by Devops to test workflows with the right branch permissions set.
> feat: add svc test repo

- src/templates/rust-svc/.github/workflows/release.yml
closes https://app.dework.xyz/arrow-air/services-1?taskId=f1bf18a9-0e0b-4dd2-af9a-f5095f09220c
> fix: only update CHANGELOG.md on main release

- src/templates/rust-svc/.github/workflows/release.yml
closes https://app.dework.xyz/arrow-air/services-1/view/board-l4x57ozt?taskId=fed3fd60-8095-4ee8-837b-05ff612753d7
> fix: only release patch versions for develop

- src/templates/rust-all/.github/workflows/rust_ci.yml
> chore: add ut stats comment

- src/repositories_rust.tf
- src/templates/rust-svc/.github/workflows/post_release.yml
Also fixes svc-storage where not all workflow files were being deployed due to overrides
> feat(rust-svc): add docs publish action

- .cspell.project-words.txt
- .make/base.mk
- src/templates/all/.make/python.mk
In tangent with https://github.com/Arrow-air/tools/pull/25
> chore: improve python workflow

- src/repositories_terraform.tf
- src/templates/all/.make/terraform.mk
- src/templates/tf-all/.env.base.tftpl
- src/templates/tf-all/Makefile
Requires successful build and deploy from https://github.com/Arrow-air/tools/pull/29 merge
> feat(terraform): make with tfenv docker

- src/templates/all/.make/python.mk
In my last PR I was editing the file for `tf-github`, not the template file.
> chore: push python workflow to all repos

- src/modules/github-repository/main.tf
Fixing failing apply on private repositories due to new security settings:
https://github.com/Arrow-air/tf-github/actions/runs/4726845753/jobs/8386829192#step:11:11243
> fix: private repo fails on security settings

- src/main.tf
🎉 HearHear is now a part of Arrow DAO!
> feat: add HearHear repos

- src/repositories_nuxt.tf
https://app.dework.xyz/arrow-air/cargo-32992?taskId=10f109b2-31d7-4ac5-bfe5-0d24b5bde002
> feat: add scanner mobile app repository

- src/templates/all/.make/base.mk
- src/templates/all/.make/rust.mk
- src/templates/rust-all/.github/workflows/rust_ci.yml
- src/templates/rust-svc/Dockerfile
- src/templates/rust-svc/docker-compose.yml
Add's specific target for unit tests and integration test coverage
Updates docker image tags for rust dockers
> feat(rust-svc): add target for integration test coverage

- .cspell.project-words.txt
- src/main.tf
- src/repositories_pod.tf
- src/repositories_templates.tf
Attempting to add a template repo for future pod projects, and two new repos. 1) project template
2) dao-gbc
3) dao-governance
+ Fix naming of files, repos
+ Fix pod naming change
+ Add pod repos file, no templates initialized
> feat: add 1 template for pods, 2 repos

- src/main.tf
Arrow Air governance has commissioned the creation of a new repo for housing Arrow Improvement Proposals (AIPs). This repo will be owned and managed by the governance team.
> Add new AIP repo for Arrow governance

- src/repositories_pod.tf
The Arrow Air engineering team has commissioned the creation of a repository dedicated to Project Feather. This repo is to be built from the template repo "pod-project-template".
> Add new Project Feather repo
