src/modules/github-repository/main.tf

Some of the branch protection rules are limited to public repositories only. It's not completely clear during the plan step if the rules are allowed to be applied or not.
I can't find the list of allowed rules for private repositories in the [Terraform provider docs](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection) either, but I'm going to assume we're not allowed to set any of the settings in the `required_pull_request_reviews` setting.
In addition, I've set the CODEOWNERS file to allow override if it already exists. I think it's fine to keep this managed by Terraform.

required_pull_request_reviews can not be set on private repositories

---

src/modules/github-repository/main.tf
src/modules/github-repository/variables.tf

- Removing `github_branch_protection` again for private repositories as the entire resource is not supported for private repositories unless the Arrow organization is upgrade to `GitHub Pro`.
-  Fix merge order of `local.protected_branches` so that the provided `default_branch_protection_settings` variable will not be overwritten by the defaults of the `protected_branches` variable.
- Added `github_branch_protection.all` resource for public repositories to enforce specific settings on all branches.
- Added `terraform_app_node_id` variable to add the `arrow-tf-github-repositories` GitHub App to the `pull_request_bypassers` list so it can still manage specific files even though branch protections are in place.
- Introduced new option to override the `allows_force_pushes` setting for …

Fixes module bugs

---

src/modules/github-repository/main.tf

When a template name is being passed to the repository module, we were using a `for_each` loop to detect if the template block needs to be set.
This loop generates a list of strings, where the iterator `key` will be the list index. We should instead use the iterator `value` to get the template name.

Bugfix: repository template name

---

README.md
src/main.tf
src/modules/github-repository/main.tf
src/moved.tf
src/repositories_rust.tf
src/repositories_templates.tf
src/repositories_terraform.tf

- Use the module to create template repositories
- Some re-organization of the repositories_*.tf files to make it easier to find the 'repos' key to create new repositories
- Started on the README.md

Template repository branch protections

---

src/main.tf

Since our benchmarks are also written in Rust, we should add the default files to the benchmarks repository as well. 
I noticed not all of the files were formatted correctly.

Add the default rust files to our benchmarks repo

---

src/modules/github-repository/variables.tf

Since we've enforced signed commits on all branches, we can't push through any file changes made with Terraform since the Terraform bot isn't able to sign the commits. (See: https://github.com/Arrow-air/tf-github/runs/8096966295?check_suite_focus=true#step:10:948)
One option is to allow administrators to bypass the branch protections which is part of this PR.
Currently, we don't provide administrator permissions to anyone except Terraform.

Allow Terraform bot to make commits without signing

---

src/templates/rust-all/.editorconfig
src/templates/rust-all/.github/workflows/editorconfig_check.yml
src/templates/rust-all/.github/workflows/pr_rebase.yml
src/templates/rust-all/.github/workflows/python_ci.yml
src/templates/rust-all/.github/workflows/rust_ci.yml
src/templates/rust-all/Makefile.tftpl

Not all ci files are setting the TERM env making the ci job fail on the `make` step.
Due to the Makefile being a template and not being matched correctly, the .editorconfig file changes all tabs into spaces.

Fix ci issues

---

src/repositories_rust.tf

More information in Services CONOPS
svc-scheduler is a busy bee and should not be directly handling requests from customers
svc-cargo, svc-rideshare, and svc-charter will handle these requests from web and mobile apps. They will handle the back and forth with customers, confirming flights, etc.
May also grab information about the aircraft, components, etc. if the customer requests it, so these requests don't go directly to svc-storage

Add svc-cargo

---

src/templates/rust-all/.editorconfig
src/templates/rust-all/Makefile.tftpl

The docker container did not get the right `workdir` param passed, so running the editorconfig check would not actually check our source code.
This change fixes the `editorconfig-test` make target and in addition fixes formatting errors in the Makefile itself.
The editorconfig configuration has been updated to allow 2 spaces for `toml` and `yaml` files too.

feat(editorconfig): fix config file and Makefile errors

---

src/templates/rust-all/.gitignore.tftpl

We need to exclude .DS_Store files for contributors working with MacOS.

Add DS_Store in gitignore template

---

src/repositories_rust.tf
src/templates/rust-all/.cargo-husky/hooks/pre-commit

Using the `test` target will make sure all tests are being run which are also tested by the github action.
In addition, fixed a bug where the file templates were given the wrong `name` for new rust service projects.

fix(rust-all): use 'test' target in pre-commit

---

src/modules/github-repository/main.tf
src/modules/github-repository/variables.tf
src/modules/github-repository/versions.tf
src/outputs.tf
src/versions.tf

This PR requires some manual state edits prior to merge to prevent these changes to be made:
```
- resource "github_branch" "branch" {
- branch        = "develop" -> null
- etag          = "W/\"afde9042310a362071d3e87e896e3c425c892bed00271b1f90657afeb6b85066\"" -> null
- id            = "lib-router:develop" -> null
- ref           = "refs/heads/develop" -> null
- repository    = "lib-router" -> null
- sha           = "c9c88ace24720ec6bc9391438a8c8b57eedba38b" -> null
- source_branch = "main" -> null
- source_sha    = "0e0c9c37b55e0eb9cad4fa5456134a58df941703" -> null
}
+ resource "github_branch" "branch" {
+ branch        = "main"
+ etag          = (known after apply)
+ id            = (known after apply)
+ ref           = (known after apply)
+ repository    = "lib-router"
+ sha …
```

fix: Create repo from template

---

src/main.tf

`atc-core` is the central library of Air Traffic Control (ATC) assets, UI elements, etc.
There is a goal to produce a video game alongside the actual ATC software, to act as a training and recruitment tool. The game would be disconnected from any real operations, but would feature up-to-date interfaces from real ATC software.
To that end, this crate is a  _library_ and not a binary. Binary crates `atc-game` and `atc-real` (actual name TBD) will import this library to populate interfaces.

:hatching_chick: Create ATC software library

---

.cspell.config.yaml
src/templates/all/.make/cspell.mk
src/templates/all/.make/markdown.mk

link-checker config needed for website checks
ignore webflow.js in the website, wall of text
With this method we don't need to include .cspell.project-words.txt or .link-checker.config.json if they're unnecessary for the repo, they'll get auto-created in CI and allow things to run without erroring out due to lack of config

fix: Add webflow to ignore paths, auto-create link checker and cspell config files

---

src/repositories_templates.tf

Problem:
- svc-template-rust is being populated with the "all" Makefile and not the Makefile.tftpl
- svc-template-[python & typescript] weren't getting provisioned with any files
Solution:
- I believe there was some overwriting going on, moved the file merge and template formatting to the module level like repositories_rust.tf does

fix: Template provision

---

.github/workflows/terraform.yml
src/modules/github-repository/main.tf
src/repositories_rust.tf

Make sure the Dockerfile is deployed to al svc-* repositories
Only allow 1 terraform apply run at a time
Remove state locking on terraform plan actions
Remove require_signed_commits again for personal branches

Multiple chore commits

---

src/templates/all/.make/docker.mk
src/templates/rust-all/Makefile.tftpl

The docker build-arg did not have the `PACKAGE_NAME` set properly.
Also fixed the `DOCKER_PORT` which is set to 8000 in the rust server.

fix(docker): build package name was not provided properly

---

src/templates/all/.make/editorconfig.mk
src/templates/rust-all/Makefile.tftpl

This adds `editorconfig-tidy` - uses eclint under the hood to fix common issues like whitespaces
Updates `tidy` to include `editorconfig-tidy` to format files in one command

add make editorconfig-tidy and format-all targets

---

src/modules/github-repository/main.tf

We've been running into issues when trying to force push rebased commits into our personal branches due to Terraform commits not being signed.
I've found out that removing the custom `commit_email` and `commit_author` settings from the file creation resource, will allow GitHub to automatically sign the commits since the proper email and author values will be used.
In preparation for commit message validations in the future, I've also changed the commit message to be valid according to the conventional commit specs.

fix: terraform app signed commits

---

.cspell.project-words.txt
src/repositories_rust.tf
src/templates/all/.make/rust.mk
src/templates/rust-svc/Dockerfile
src/templates/rust-svc/docker-compose.yml

Creating a `rust-svc` specific templates directory again for files only needed for our svc repositories.
Adding a docker-compose configuration file to make sure the server is running when calling the cargo example target.
Providing a specific cargo-run function and separating the docker commands for rust completely.

feat(examples): use docker compose to run examples

---

.cspell.project-words.txt
src/main.tf
src/repositories_rust.tf
src/templates/all/.commitlintrc.yml
src/templates/all/.make/base.mk
src/templates/all/.make/commitlint.mk
src/templates/rust-all/.cargo-husky/hooks/commit-msg
src/templates/rust-all/.github/workflows/rust_ci.yml
src/templates/rust-all/.github/workflows/sanity_checks.yml
src/templates/rust-all/Makefile.tftpl

In preparation for automatic release and changelog generation, I've added commitlint to the workflows so we can start writing proper commit messages for changelog tracking.
In addition, a comment will be added to each PR showing a preview for the Changelog output.

feat(sanity checks): add check for commit messages

---

src/main.tf
src/repositories_rust.tf
src/repositories_templates.tf
src/templates/all/.make/base.mk
src/templates/all/.make/docker.mk
src/templates/all/.make/rust.mk
src/templates/all/.make/toml.mk
src/templates/benchmarks/Makefile
src/templates/rust-all/.taplo.toml
src/templates/rust-all/Makefile.tftpl
src/templates/rust-svc/.github/workflows/release.yml
src/templates/rust-svc/Dockerfile
src/templates/rust-svc/docker-compose.yml

This PR will add a release workflow for all `rust-svc` repositories.
Most of the magic can be found here:
https://github.com/Arrow-air/tf-github/pull/56/files#diff-025c90e98d0cc2a8302c5d014b0c557f3556f1e9087823a9b24008d5ff864b55
Release process:
- Checkout PR target branch
- Get a list of all the commit messages part of the branch
- Determine which tag should be used based on the commit message subjects (semantic-release)
- Generate Changelog based on commit messages
- Bump package version to new tag
- Commit and push Changelog and package version changes
- Set tag on latest sha
- Build and push docker image with new tag
- Create Release in GitHub with new tag
The PR also adds some fixes for the docker-compose workflow to run rust example.
After we've merged develop into main, we need to …

feat(rust-svc): release workflow

---

src/repositories_rust.tf

I noticed the release workflow was not properly added to the terraform configuration for the rust svc repositories.
The `sanity_checks.yaml` was a copy/paste from the `rust_default.files` but I'd forgotten to change it to the right file name.

fix(release): deploy release workflow for svc

---

src/templates/all/.make/rust.mk
src/templates/rust-svc/Dockerfile
src/templates/rust-svc/docker-compose.yml

After being able to run a full end-to-end test using the svc-template-rust repository which has the latest files provisioned by Terraform, I ran into a couple of bugs.
This PR should fix these issues. 
A related PR has been created on svc-template-rust, to have a fully working grpc example using the `make rust-example-grpc` command.

fix(docker-compose): health check and env vars

---

src/repositories_rust.tf
src/templates/all/.make/rust.mk
src/templates/rust-svc/.github/workflows/release.yml
src/templates/rust-svc/Dockerfile

The release pipeline still had some issues which have been manually fixed. This PR should make sure the manual fixes don't get overwritten when running Terraform again.
From the Dework task:

fix(rust-svc): release and docker make targets

---

.cspell.project-words.txt
src/main.tf
src/modules/github-repository/variables.tf
src/repositories_nuxt.tf
src/repositories_rust.tf
src/repositories_templates.tf
src/repositories_terraform.tf
src/templates/all/.commitlintrc.yml
src/templates/nuxt-all/.github/workflows/sanity_checks.yml
src/templates/nuxt-all/.gitignore
src/templates/nuxt-all/.husky/commit-msg
src/templates/nuxt-all/.husky/pre-commit

Adding files and resources for nuxt repositories.
The template repository will be expanded later, once we have created a good setup in the `web-cargo-shipper` nuxt repository.
Also fixing release automation by just using the Terraform Github App.
Apps are not allowed to access other private app's in the organization, thus making it impossible for the Terraform Github App to check on the Release automation app's ID to add it to the list of commit bypasses.
For now, we'll just release with the Terraform App itself, which already has the right permissions.

feat(web-nuxt): add web repositories and resources

---

src/main.tf
src/repositories_rust.tf
src/templates/all/.make/docker.mk
src/templates/all/.make/env.mk
src/templates/rust-lib/.env.base.tftpl
src/templates/rust-lib/Makefile
src/templates/rust-svc/.env.base.tftpl
src/templates/rust-svc/Makefile

* `.env` files are now pulled into make (by `.make/env.mk`), so runtime variables only have to be defined in one place
* terraform deploys a `.env.base` for the rust-svc and rust-lib repos that contains some base settings such as ports and package/docker names
* each repo can optionally have their repo-specific settings in a `.env.repo` file
* Whenever 'make' runs it'll check for the presence of a `.env` file, if missing it'll concatenate both `.env.base` and `.env.repo` and write this to `.env` for hopefully sane defaults. In case new settings are added later to the terraform-managed files they also get picked up as new keys by make and will automagically be added to the local .env file. 
* This also means the Makefile for rust-svc and rust-lib can be generic without if statements

chore(.env): restructured .env file handling

---

src/repositories_rust.tf

Last TF push produced a file named `.env.base.tftpl` in all svc repos: https://github.com/Arrow-air/svc-cargo/commit/89a18274632c2f62b52d4ae31a93838921dae0ab
Since .env.base wasn't found, weird stuff:

fix(.env): remove tftpl ending

---

src/versions.tf

There seems to be a but in our latest provider, causing issues in applying our plans:
https://github.com/integrations/terraform-provider-github/issues/1373

fix(provider): github provider bug in 5.9.0

---

src/templates/all/.make/env.mk

https://stackoverflow.com/questions/53836858/shell-function-in-gnu-makefile-results-in-unterminated-call-to-function-shel

fix(make): need extra escape for 4.2 and older

---

.editorconfig
.gitignore
src/.terraform.lock.hcl
src/versions.tf

We don't want the provider version 5.9.x yet, as it still seems to be broken.
Shipping the lock file to git this time as well, so github actions won't automatically pick a newer version.

fix(lock): ship lock file to pin version

---

.editorconfig
src/repositories_rust.tf
src/templates/all/.editorconfig
src/templates/rust-all/LICENSE.tftpl

Adding a template for our LICENSE file to be deployed to all rust repositories.
Assumptions:
- ~~We'll be releasing under v0 at first~~
- ~~Change date for v0 will be at 2024-12-01 (or should we set it to 2025-01-01?)~~
- ~~Change date for all minor / fix releases under V0 will be listed in the repositories inside the `license/v0-license-date` file~~
- ~~When releasing v1, we'll be updating all svc repo's through Terraform again with a new LICENSE file~~
Questions:
- Do we actually want to keep the major version in sync for all our rust repo's? (or will they have their own release cycle and do we want to provide the LICENSE file trough the template repository instead)
- Answer: The LICENSE `Change Date` Parameter has been updated to use more generic wording so we don't need to update the …

feat(rust): add LICENSE file

---

src/repositories_rust.tf
src/templates/rust-all/.github/workflows/nightly.yml

4 AM UTC execution of `cargo build` and link checker
Will catch broken dependencies, especially if grpc APIs are updated in a way that makes them incompatible with the client (f32 -> f64 changes, etc.)

feat: add nightly build for develop branch

---

.cspell.project-words.txt
src/repositories_rust.tf

The initial implementation of ccsds.rs at https://github.com/Arrow-air/svc-telemetry/pull/2 raised some questions.
`lib-ccsds` should be `#![no_std]` by default so it can be used in safety-critical RTOS (disable heap allocation)
The implementation at  https://github.com/Arrow-air/svc-telemetry/pull/2 should be offered through a `std` feature.

feat: add lib-ccsds

---

src/repositories_rust.tf
src/templates/all/.cspell.config.yaml
src/templates/all/.make/rust.mk
src/templates/rust-all/.gitignore.tftpl
src/templates/rust-svc/.github/workflows/api_docs.yml

NOTE: Does not push to AWS or regenerate Docusaurus docs yet.
Example: https://github.com/Arrow-air/svc-cargo/actions/runs/3833748192/jobs/6525498455
This would allow REST API generation like so: https://github.com/Arrow-air/svc-cargo/blob/0ffdaf6299e2aad4bbf2a3abcfc71a37c362d1ed/server/src/main.rs#L175

feat: add api generation commands

---

src/templates/all/.cspell.config.yaml
src/templates/all/.make/rust.mk
src/templates/rust-all/.github/workflows/rust_ci.yml
src/templates/rust-all/.gitignore.tftpl

NOTE: Tarpaulin requires `--security-opt seccomp=unconfined`, investigating if this is going to be a security issue if we only use it in GitHub actions for coverage tests and NOT deployment
UPDATE:
Moving this back out of draft, the `svc-devops-test` repo is very helpful
Demonstrated what UT coverage looks like: https://github.com/Arrow-air/svc-devops-test/pull/24
Output on Coveralls: https://coveralls.io/github/Arrow-air/svc-devops-test (log in to see source code)

feat: add cargo tarpaulin to Makefile and workflow

---

src/templates/rust-svc/.github/workflows/release.yml

Seems like the `push` event gets triggered both on the merge commit and the last commit of the merge itself. Using the pull request `close` event now, but making sure it's closed with a merge before we run.

fix(rust-svc): prevent double trigger release workflow

---

src/templates/rust-svc/.github/workflows/autosquash.yml
src/templates/rust-svc/.github/workflows/release.yml

Since we're rebasing the develop branch after pushing our release changes, the tag would be placed on the wrong ref.
This would fail the docker build step in the `post-release` workflow.
This PR fixes this issue.

fix(rust-svc): docker build after release

---

src/templates/all/.editorconfig

The latest mstruebing/editorconfig-checker docker image was [failing on the Cargo.lock file](https://github.com/Arrow-air/svc-storage/actions/runs/4152748810/jobs/7184132353). Where it seems to have ignored the file in the past, it now also started checking it and expecting 4 spaces as ident.
This pr should fix the issue.

fix(editorconfig): don't test spaces for Cargo.lock file

---

src/repositories_rust.tf

`svc-telemetry` needs to define its own docker-compose file due to dependencies on Redis

feat: svc-telemetry custom docker compose

---

src/templates/all/.make/rust.mk
src/templates/rust-svc/.github/workflows/release.yml

Make sure we have all build output files available before creating the client-grpc publish package.
Also adds a `workflow_dispatch` trigger on the release workflow to manually trigger a release on the develop branch.

fix(rust-svc): grpc client publish

---

src/templates/all/.make/markdown.mk

The 'stable' version doesn't properly use the config file at the moment. Pinning to an older, still working, version.

fix: markdown link check

---

src/templates/rust-svc/.github/workflows/release.yml

- Added `continue-on-error` for rebase auto squash step on develop branch. It will not fail the release process anymore. Any failed rebases can be manually fixed afterward if needed.
- Fixes rebase step on main branch merge. Will now reset develop branch to origin/main instead.

fix(rust-svc): rebase steps in release process

---

src/moved.tf
src/repositories_terraform.tf
src/templates/all/.cspell.config.yaml
src/templates/all/.make/terraform.mk
src/templates/tf-all/.gitignore
src/templates/tf-gcp/.env.base.tftpl
src/templates/tf-gcp/.github/workflows/terraform.yml
src/templates/tf-gcp/Makefile
src/templates/tf-onboarding/.github/workflows/terraform.yml

- Moving `gcp` repositories to a separate map so we can provide specific files such as workflows.
- Additional makefile fixes for Terraform targets.
- Added workflow to run Terraform for multiple workspaces

feat(terraform): github actions fixes

---

Makefile
src/templates/tf-all/Makefile

Fixing missing DOCKER_NAME for tf-github and tf-onboarding after changes made in https://github.com/Arrow-air/tf-github/pull/108

fix(tf-github): workflow missing DOCKER_NAME

---

src/repositories_embedded.tf
src/templates/stm32-all/.gitignore
src/templates/stm32-all/.make/st.mk
src/templates/stm32-all/LICENSE
src/templates/stm32-all/Makefile

Adding BSD-3 license because of a HAL conf file acquired from STMicro: https://github.com/Arrow-air/embedded-template-stm32/blob/bc72fc4facdd25c1b8cc6a750c44793284de46d1/stm32f4xx_hal_conf.h

feat: add flash capability to STM32

---

src/repositories_rust.tf
src/templates/all/.make/rust.mk
src/templates/rust-all/.github/workflows/release.yml
src/templates/rust-all/.github/workflows/rust_ci.yml

Added caching action, but still seems to compile when it shouldn't.
Increased tarpaulin timeout to 5 min so tests can continue to run even though they exceed the default 60sec due to recompile.
Also added a fix for library build-and-deploy action.

fix(rust): lib coverage tests and release

---

src/templates/all/.make/markdown.mk
src/templates/rust-all/.github/workflows/rust_ci.yml

Now that we also use this workflow for lib repo's, we should just check based on file name / extension.
Not all repositories have the same folder structure.

ci(rust): trigger on file changes instead of paths

---

src/templates/all/.make/rust.mk
src/templates/rust-svc/Dockerfile

Split the package feature options per cargo target:
PACKAGE_TEST_FEATURES
PACKAGE_BUILD_FEATURES
PACKAGE_RELEASE_FEATURES
Provide PACKAGE_RELEASE_FEATURES env var to Dockerfile as well.
Also updates the deprecated `--all` flag with `--workspace`

fix(make): allow different features per cargo target

---

src/templates/all/.make/rust.mk
src/templates/rust-svc/.dockerignore
src/templates/rust-svc/Dockerfile
src/templates/rust-svc/Makefile

Inspired by https://github.com/Arrow-air/tf-github/pull/122
Should speed up local builds using a docker cache mount for the `cargo/registry` and ignoring unneeded folders for `COPY`.

chore(rust-svc): speed up local build target

---

src/templates/all/.github/workflows/sanity_checks.yml
src/templates/rust-all/.github/workflows/python_ci.yml
src/templates/rust-all/.github/workflows/rust_ci.yml
src/templates/rust-all/.github/workflows/sanity_checks.yml

Python, Rust, and Sanity Checks were only running on the branches being merged into develop and main, but not develop and main themselves
https://github.com/Arrow-air/svc-cargo/actions

feat: run sanity, python, rust workflows on push

---

src/repositories_rust.tf
src/templates/all/.make/docker.mk
src/templates/all/.make/rust.mk
src/templates/rust-svc/.github/workflows/post_release.yml
src/templates/rust-svc/Dockerfile
src/templates/rust-svc/docker-compose.yml

Adds `docker-build-dev` make target so we can build a docker image with the `stub_backends` feature enabled. This can then be used to run the `example` without the need of additional backends.
Merge after #136 
After apply the following repositories will need their docker-compose.yml files updated as well:
- svc-telemetry
- svc-gis
- svc-storage
- svc-compliance

feat(rust-svc): add target for docker dev build

---

src/templates/rust-all/.github/workflows/release.yml
src/templates/rust-svc/.github/workflows/post_release.yml

This adds the latest (main branch) and latest-develop (develop branch) tags to the git repositories if a release is done on the corresponding branch.
In addition, the docker image now also gets the latest-develop tag on develop releases

feat(rust-all): add 'latest' tag on release

---

src/templates/all/.cspell.config.yaml

An update from cspell has introduced in issue when running our automated checks, where additional configurations found in the child path would also be included.
This should fix that issue for us.

fix: cspell should not auto search additional config files

---

.cspell.project-words.txt
src/main.tf

Per Sleety's request, the repo ought to be named `dao-aips`

Fix naming of AIP repo
